### PR TITLE
Test on all current LTS versions of node

### PR DESCRIPTION
**Pull request by TehShrike**

### CODE REVIEW

**Comment by TehShrike** [comment]
The tests only pass on node 10 right now - is this known/intended?

**Comment by mathiasbynens** [comment]
This is intentional; we’re testing in the Node.js version specified in `.nvmrc`.

Note that the build step produces libraries that can be consumed in older Node.js versions.

**Comment by TehShrike** [comment]
What would it take to get automated tests of those distributed files?

I upgraded one of my libraries to use jsbi instead of jsbn, and [the tests fail on node 6](https://travis-ci.org/TehShrike/financial-arithmetic-functions/jobs/454211107).

I wanted to come here to make sure that the library was being tested under node 6, but don't see that happening at the moment.

**Comment by mathiasbynens** [comment]
Hey @TehShrike, could you please try again with the latest published JSBI version? It should resolve the problem.

**Comment by TehShrike** [comment]
💯 https://travis-ci.org/TehShrike/financial-arithmetic-functions/builds/455524278

**Comment by TehShrike** [comment]
So, this PR should be closed I imagine, but I'd still feel better if there were automated tests of the distributed files in all supported environments... should I open an issue?

**Comment by mathiasbynens** [comment]
Yes, please file a separate issue titled something like “Test the distributed files in all supported environments”. Let’s close this one.

**Pull request closed without merging**
