### PR TITLE
Fix __fromDouble for 30-bit digits

### LINKED ISSUE #63: conversion from huge numbers does not match BigInt
JSBI.BigInt(4.4384296245614243e+42).toString()
gives 
"4438429624561424525564590093179539127533568"
should give
"4438429624561424320047307980392507864252416"

### PR DESCRIPTION
**Pull request by jakobkummerow**
Fixes #63.

### CODE REVIEW

**Comment by Yaffle** [comment]
hm...
JSBI.toNumber(JSBI.BigInt('3361387880631608742970259577528807057005903'))
gives
3.3613876448967815e+42
not
3.361387880631609e+42
is it another bug?

**Comment by jakobkummerow** [comment]
@Yaffle : yes, conversion in the opposite direction, so separate bug. I'll amend the fix.

**Comment by Yaffle** [comment]
@jakobkummerow thanks

**Review by mathiasbynens — APPROVED** [review]

**Comment by jakobkummerow** [comment]
@Yaffle Thanks for all the reports!

@mathiasbynens Thanks for reviewing!

**Pull request merged**
