### PR TITLE
Bump TS to v4.4.2 and add noImplicitOverride.

### PR DESCRIPTION
**Pull request by 12wrigja**

### CODE REVIEW

**Comment by 12wrigja** [comment]
For what it's worth, I do want to land this, but I don't think it's worth issuing a patch release for it as the end-user code is unlikely to change significantly. Thoguhts?

**Review by mathiasbynens — APPROVED** [review]

**Comment by mathiasbynens** [comment]
> For what it's worth, I do want to land this, but I don't think it's worth issuing a patch release for it as the end-user code is unlikely to change significantly. Thoguhts?

I see what you're saying. OTOH, version numbers are free, so I wouldn't mind cutting a release (especially now that the process is almost entirely automated).

**Comment by HolgerJeromin** [comment]
The result is that any consumer of the `.d.ts` needs to have TS4.4. Not sure if this is a problem, but would be at our code base.

**Comment by 12wrigja** [comment]
It's certainly true that it's hand-crafted - the typings existed before JSBI was migrated to TS sources. I did attempt to have this file automatically generated from the .d.ts file, but there were enough differences between the hand-written one and the autogenerated one that I didn't want to complicate migrating the sources over.

What build system is your codebase using? Does it use the sources directly, or the .d.ts in combination with one of the build artifacts from npm?

**Comment by HolgerJeromin** [comment]
Sorry. This was not clear. 
We are not using JSBI. 
But we have customers which are consumers of our .d.ts files which are using ts3.9.x

So perhaps there are JSBI users which are using an older ts version, too.

**Pull request merged**
